apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acc-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: acc-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  # source:
  #   git:
  #     ref:
  #       branch: main
  #     url: https://github.com/vmware-tanzu/application-accelerator-samples.git
  #   subPath: acc-demo
